version: "3"

services:

  postgresql:
    build: 
      context: .
      dockerfile: PostgreSql.DockerFile
    expose:
      - "5432"
    ports:
      - "15432:5432"
    networks:
      - turkcell_poc

  redis:
    image: "redis:alpine"
    expose:
      - "6379"
    networks:
      - turkcell_poc
    depends_on:
      - "postgresql"

  servicediscovery:
    image: service_discovery:0.0.1-SNAPSHOT
    networks:
      - turkcell_poc
    expose:
      - "8761"
    ports:
      - "8761:8761"
    environment:
      - JAVA_OPTS=
        -DEUREKA_SERVER=http://servicediscovery:8761/eureka
    depends_on:
      - "redis"

  gateway:
    image: gateway:0.0.1-SNAPSHOT
    ports:
      - "8080:8080"
    networks:
      - turkcell_poc
    environment:
      - JAVA_OPTS=
        -DEUREKA_SERVER=http://servicediscovery:8761/eureka
    depends_on:
      - "redis"
      - "servicediscovery"

  employees:
    image: employee_service:0.0.3-SNAPSHOT
    expose:
      - "9003"
    networks:
      - turkcell_poc
    environment:
      - JAVA_OPTS=
        -DEUREKA_SERVER=http://servicediscovery:8761/eureka
    depends_on:
      - "servicediscovery"
      - "gateway"

  feeds:
    image: feed_service:0.0.1-SNAPSHOT
    expose:
      - "9002"
    networks:
      - turkcell_poc
    environment:
      - JAVA_OPTS=
        -DEUREKA_SERVER=http://servicediscovery:8761/eureka
    depends_on:
      - "servicediscovery"
      - "gateway"

  dashboard:
    image: dashboard_service:0.0.1-SNAPSHOT
    expose:
      - "9006"
    networks:
      - turkcell_poc
    environment:
      - JAVA_OPTS=
        -DEUREKA_SERVER=http://servicediscovery:8761/eureka
    depends_on:
      - "servicediscovery"
      - "gateway"

  files:
    image: file_service:0.0.1-SNAPSHOT
    volumes:
      - /data/turkcell_poc/upload:/upload
    expose:
      - "9004"
    networks:
      - turkcell_poc
    environment:
      - JAVA_OPTS=
        -DEUREKA_SERVER=http://servicediscovery:8761/eureka
    depends_on:
      - "servicediscovery"
      - "gateway"

  auth:
    image: auth_service:0.0.1-SNAPSHOT
    expose:
      - "9005"
    networks:
      - turkcell_poc
    environment:
      - JAVA_OPTS=
        -DEUREKA_SERVER=http://servicediscovery:8761/eureka
    depends_on:
      - "servicediscovery"
      - "gateway"


networks:
  turkcell_poc:

